"""delete uniqe constraint from workspace_invitatoins table 

Revision ID: 66816809b7df
Revises: 125bbf99956b
Create Date: 2026-07-09 12:00:25.175787

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66816809b7df'
down_revision: Union[str, Sequence[str], None] = '125bbf99956b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_workspace_invitation_email'), 'workspace_invitations', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_workspace_invitation_email'), 'workspace_invitations', ['workspace_id', 'email'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
